# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newfolderButton = QtWidgets.QPushButton(self.frame)
        self.newfolderButton.setObjectName("newfolderButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.newfolderButton)
        self.gridLayout_2.addWidget(self.newfolderButton, 4, 1, 1, 1)
        self.treeView_2 = QtWidgets.QTreeView(self.frame)
        self.treeView_2.setObjectName("treeView_2")
        self.treeView_2.header().setDefaultSectionSize(160)
        self.gridLayout_2.addWidget(self.treeView_2, 0, 2, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.frame)
        self.resetButton.setObjectName("resetButton")
        self.buttonGroup.addButton(self.resetButton)
        self.gridLayout_2.addWidget(self.resetButton, 3, 2, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.frame)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonGroup.addButton(self.deleteButton)
        self.gridLayout_2.addWidget(self.deleteButton, 1, 2, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.frame)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setDefaultSectionSize(160)
        self.treeView.header().setMinimumSectionSize(39)
        self.gridLayout_2.addWidget(self.treeView, 0, 1, 1, 1)
        self.copyButton = QtWidgets.QPushButton(self.frame)
        self.copyButton.setObjectName("copyButton")
        self.buttonGroup.addButton(self.copyButton)
        self.gridLayout_2.addWidget(self.copyButton, 1, 1, 1, 1)
        self.moveButton = QtWidgets.QPushButton(self.frame)
        self.moveButton.setObjectName("moveButton")
        self.buttonGroup.addButton(self.moveButton)
        self.gridLayout_2.addWidget(self.moveButton, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.buttonGroup.addButton(self.pushButton)
        self.gridLayout_2.addWidget(self.pushButton, 5, 1, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setObjectName("exitButton")
        self.buttonGroup.addButton(self.exitButton)
        self.gridLayout_2.addWidget(self.exitButton, 5, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup.addButton(self.pushButton_2)
        self.gridLayout_2.addWidget(self.pushButton_2, 4, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newfolderButton.setText(_translate("MainWindow", "New folder"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.moveButton.setText(_translate("MainWindow", "Move"))
        self.pushButton.setText(_translate("MainWindow", "Show F.A.Q."))
        self.exitButton.setText(_translate("MainWindow", "Exit from program"))
        self.pushButton_2.setText(_translate("MainWindow", "Take screenshot"))
